version: "3.7"

services:
  api:
    build: ./api
    command: npm start
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - ./api:/usr/app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password_to_put_in_git_ignore

  reactapp:
    build: ./app
    command: npm start
    restart: unless-stopped
    ports:
      - 8080:3000
    volumes:
      - ./app:/usr/app

  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    volumes:
      - './mongodb/database:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password_to_put_in_git_ignore
      PUID: 1000
      PGID: 1000
    ports:
      - 27017:27017
    restart: unless-stopped

