version: "3.7"

services:
  app:
    image: node:12-alpine
    restart: always
    command: sh -c "yarn install && yarn run dev"
    ports:
      - 8080:8080
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password_to_put_in_git_ignore

  db:
    image: mongo
    restart: always
    volumes:
      - './data:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password_to_put_in_git_ignore
