version: "3.7"

services:
  api:
    container_name: api
    build: ./api
    command: npm start
    volumes:
      - ./api:/app
    ports:
      - 9000:9000
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - api-network

  reactapp:
    container_name: reactapp
    build: ./app
    command: npm start
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    restart: unless-stopped

  mongodb:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    volumes:
      - './mongodb/database:/data/db'
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: v3JG2@wNeht9
      MONGO_INITDB_DATABASE: app
    restart: unless-stopped
    networks:
      - api-network

